version: "3.9"

services:
  api:
    build: .
    container_name: habit-tracker-api
    command: uvicorn habit_tracker.interfaces.api.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Volume mount for live reload
    environment:
      PYTHONUNBUFFERED: "1"
